language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: melissari1997
    token: 26fc90c7e2ecbcdaf2055a3f3001aba05d4ef09b # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
   - mvn verify sonar:sonar 
   #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify -DfailIfNoTests=false sonar:sonar
  # - mvn package sonar:sonar

after_success:
   - mvn verify -Pcoverage

